name: CI

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1

      - name: Install Composer Dependencies
        run: composer install

      - name: Run Unit Tests
        run: phpunit --configuration path/to/phpunit.xml

      - name: Check Test Results
        run: |
          if [ $? -ne 0 ]; then
            echo "Tests failed. Pushing code is not allowed."
            exit 1
          fi
        shell: bash
